/**
 * 
 */
package cn.seddat.openapi.weather.meteor;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.codehaus.jackson.map.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.google.common.base.Splitter;

import cn.seddat.openapi.HttpRequest;
import cn.seddat.openapi.weather.Config;

/**
 * @author gengmaozhang01
 * @since 2014-3-15 下午2:18:44
 */
@Service
public class ForecastWeatherQuery {

	private static final Log log = LogFactory.getLog(RealtimeWeatherQuery.class);

	@Autowired
	private HttpRequest httpRequest;

	/**
	 * 抓取天气预报信息
	 * 
	 * @author gengmaozhang01
	 * @since 2014-2-22 下午8:51:50
	 */
	public Map<String, Object> query(String citycode) throws Exception {
		if (citycode == null || citycode.isEmpty()) {
			throw new IllegalArgumentException("citycode is required");
		}
		// 注意：两个接口返回的数据结构不一致
		boolean isApi = false;
		if (isApi) {
			return this.queryForecastWeatherByAPI(citycode);
		}
		Map<String, Object> result = this.queryForecastWeatherByHTML(citycode);
		log.info("forecast weather: " + result);
		return result;
	}

	/**
	 * 通过API获取天气预报信息
	 * 
	 * @author gengmaozhang01
	 * @since 2014-2-23 上午1:45:30
	 * @deprecated 2014.02.19号后数据更新不及时
	 */
	private Map<String, Object> queryForecastWeatherByAPI(String citycode) throws Exception {
		// request
		String url = Config.getInstance().getForecastUrl(citycode);
		String content = this.request(url);
		if (content == null || content.isEmpty()) {
			throw new Exception("query forecast weather failed, result is empty");
		}
		log.info("forecast weather: " + content);
		// parse
		ObjectMapper mapper = new ObjectMapper();
		@SuppressWarnings("unchecked")
		Map<String, Object> value = mapper.readValue(content, Map.class);
		return value;
	}

	/**
	 * 通过抓取网页获取天气预报信息
	 * 
	 * @author gengmaozhang01
	 * @since 2014-2-23 上午1:46:21
	 */
	private Map<String, Object> queryForecastWeatherByHTML(String citycode) throws Exception {
		// request
		String url = Config.getInstance().getWeatherPageUrl(citycode);
		String content = this.request(url);
		if (content == null || content.isEmpty()) {
			throw new Exception("query forecast weather failed, result is empty");
		}
		// log.info("forecast weather: " + content);
		// parse
		Map<String, Object> weatherinfo = new HashMap<String, Object>();
		weatherinfo.put("cityid", citycode);
		// weatherinfo.put("city", "");
		// weatherinfo.put("city_en", "");
		final List<String> lines = Splitter.on('\n').trimResults().omitEmptyStrings().splitToList(content);
		// 发布时间
		String title = null;
		for (String line : lines) {
			if (line.indexOf("Generated By TurboCMS.Java") > -1) {
				int si = line.indexOf(',') + 1, ei = line.indexOf(',', si);
				if (si > -1 && ei > -1) {
					title = line.substring(si, ei);
					break;
				}
			}
		}
		String time = null;
		final SimpleDateFormat publishFormat = new SimpleDateFormat("yyyy.MM.dd HH:00");
		if (title != null && !title.isEmpty()) {
			log.info("title: " + title);
			try {
				Date date = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy", Locale.US).parse(title);
				time = publishFormat.format(date);
			} catch (Exception ex) {
				log.error("parse publish time failed", ex);
			}
		}
		if (time == null || time.isEmpty()) {
			time = publishFormat.format(new Date());
		}
		log.info("time: " + time);
		weatherinfo.put("time", time);
		// weatherinfo.put("date_y", time);
		// weatherinfo.put("fchh", time);
		// weatherinfo.put("date", time);
		// weatherinfo.put("week", time);
		// 预报信息
		List<String> tables = new ArrayList<String>();
		StringBuffer buf = new StringBuffer();
		boolean isTable = false;
		for (String line : lines) {
			if (!isTable) {
				isTable = (line.indexOf("<table") > -1 && line.indexOf("class=\"yuBaoTable\"") > -1);
			}
			if (isTable) {
				buf.append(line);
				if (line.indexOf("</table>") > -1) {
					tables.add(buf.toString());
					buf = new StringBuffer();
					isTable = false;
				}
			}
		}
		List<Map<String, String>> forecast = new ArrayList<Map<String, String>>();
		final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy.MM.dd");
		String prevTime = null, prevHalf = null;
		for (String table : tables) {
			List<String> trs = Splitter.on("</tr>").omitEmptyStrings().splitToList(table);
			for (String tr : trs) {
				int si = tr.indexOf("<tr"), ei = -1;
				if (si == -1) {
					continue;
				}
				tr = tr.substring(si + 3);
				List<String> tds = Splitter.on("</td>").omitEmptyStrings().splitToList(tr);
				// 日期
				if (tds.size() == 7) {
					time = tds.get(0);
					ei = time.indexOf("日");
					si = time.lastIndexOf(">", ei) + 1;
					time = time.substring(si, ei);
					Calendar cal = Calendar.getInstance();
					int day = Integer.parseInt(time);
					if (cal.get(Calendar.DAY_OF_MONTH) > day + 7) {
						cal.add(Calendar.MONTH, 1);
					}
					cal.set(Calendar.DAY_OF_MONTH, day);
					time = dateFormat.format(cal.getTime());
				} else {
					time = prevTime;
				}
				// 白天或夜晚
				String half = tds.get(tds.size() == 7 ? 1 : 0);
				half = half.substring(half.indexOf("<td") + 3);
				si = half.indexOf('>') + 1;
				ei = half.indexOf('<', si);
				half = (ei > -1 ? half.substring(si, ei) : half.substring(si));
				// 图片
				String image = tds.get(tds.size() == 7 ? 2 : 1);
				ei = image.indexOf("gif\"") + 3;
				si = image.lastIndexOf("/", ei) + 1;
				image = image.substring(si, ei);
				// 天气
				String weather = tds.get(tds.size() == 7 ? 3 : 2);
				si = weather.indexOf("\"_blank\">") + 9;
				ei = weather.indexOf("<", si);
				weather = weather.substring(si, ei);
				// 温度
				String temp = tds.get(tds.size() == 7 ? 4 : 3);
				si = temp.indexOf("<strong>") + 8;
				ei = temp.indexOf("<", si);
				temp = temp.substring(si, ei);
				// 风向
				String wd = tds.get(tds.size() == 7 ? 5 : 4);
				si = wd.indexOf("\"_blank\">") + 9;
				ei = wd.indexOf("<", si);
				wd = wd.substring(si, ei);
				// 风力
				String ws = tds.get(tds.size() == 7 ? 6 : 5);
				si = ws.indexOf("\"_blank\">") + 9;
				ei = ws.indexOf("<", si);
				ws = ws.substring(si, ei);
				// add
				if (!time.equals(prevTime) || !half.equals(prevHalf)) {
					Map<String, String> map = new HashMap<String, String>();
					map.put("time", time);
					map.put("half", half);
					map.put("image", image);
					map.put("weather", weather);
					map.put("temp", temp);
					map.put("wd", wd);
					map.put("ws", ws);
					forecast.add(map);
				}
				prevTime = time;
				prevHalf = half;
			}
		}
		weatherinfo.put("forecast", forecast);
		// result
		Map<String, Object> result = new HashMap<String, Object>();
		result.put("weatherinfo", weatherinfo);
		return result;
	}

	private String request(String url) throws Exception {
		Map<String, String> headers = new HashMap<String, String>();
		headers.put("Host", "www.weather.com.cn");
		headers.put("Referer", "http://www.weather.com.cn/weather/101010100.shtml");
		headers.put("Accept-Charset", "UTF-8");
		return httpRequest.request(url, headers);
	}

}
